<?php

return array(
    '' => 'site/index',
    'login' => 'site/login',
    'logout' => 'site/logout',
    'recover-password' => 'site/ForgotPassword',
    'merchant-registration' => 'registration/merchantDetails/create',
    'merchant-activation' => 'registration/merchantDetails/UserActivation',
    'buyer-activation' => 'registration/buyerDetails/UserActivation',
    'user-registration' => 'registration/buyerDetails/create',
    'merchant-home' => 'merchant/merchantDetails/home',
    'merchant-profile' => 'merchant/merchantDetails/profile',
    'merchant-editProfile' => 'merchant/merchantDetails/editProfile',
    'change_password' => 'merchant/merchantDetails/changePassword',
    'featured-ads' => 'merchant/merchantDetails/featuredAds',
    'my-sales' => 'merchant/merchantDetails/mySales',
    'request-pay' => 'merchant/merchantDetails/paymentRequest',
    'add-product' => 'merchant/products/addProduct',
    'edit-product' => 'merchant/products/Edit',
    'delete-product' => 'merchant/products/deleteproduct',
    'view-product' => 'merchant/products/View',
    'my-products' => 'merchant/products/myProducts',
    
    'products' => 'product/products',    
    'my-account' => 'buyerDetails/MyAccount',    
    'address-book' => 'buyerDetails/AddressBook',    
    'change-password' => 'buyerDetails/ChangePassword',    
    'edit-profile' => 'buyerDetails/EditProfile',    
    'my-orders' => 'buyerDetails/MyOrders',    
    'my-wishlist' => 'buyerDetails/Wishlist',    
    'my-cart' => 'cart/Mycart',    
    '<controller:\w+>/<id:\d+>' => '<controller>/view',
    '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
);

