<?php

return array(
    '' => 'site/index',
    'login' => 'site/login',
    'logout' => 'site/logout',
    'about-us' => 'site/static/page/about-us',    
    'join-our-shop' => 'site/static/page/join-our-shop',    
    'merchant' => 'site/static/page/merchant',    
    'affiliates' => 'site/static/page/affiliates',    
    'specials' => 'site/static/page/specials',    
    'privacy' => 'site/static/page/privacy-policy',    
    'terms' => 'site/static/page/terms',    
    'sitemap' => 'site/static/page/site-map',    
    'shipping-return' => 'site/static/page/shipping-return',    
    'local-vendors' => 'site/static/page/local-vendors',    
    'faq' => 'site/faq',
//    'about_us' => 'site/AboutUs',
    'contact_us' => 'site/ContactUs',
    'recover-password' => 'site/ForgotPassword',
    'merchant-registration' => 'registration/merchantDetails/create',
    'merchant-activation' => 'registration/merchantDetails/UserActivation',
    'buyer-activation' => 'registration/buyerDetails/UserActivation',
    'user-registration' => 'registration/buyerDetails/create',
    'merchant-home' => 'merchant/merchantDetails/home',
    'orders' => 'merchant/merchantDetails/myOrders',
    'plans' => 'merchant/merchantDetails/UpgradePlan',
    'merchant-dashboard' => 'merchant/merchantDetails/dashboard',
    'merchant-profile' => 'merchant/merchantDetails/profile',
    'merchant-editProfile' => 'merchant/merchantDetails/editProfile',
    'change_password' => 'merchant/merchantDetails/changePassword',
    'featured-ads' => 'merchant/merchantDetails/featuredAds',
    'my-sales' => 'merchant/merchantDetails/mySales',
    'most-purchased' => 'merchant/merchantDetails/mostPurchased',
    'most-viewed' => 'merchant/merchantDetails/mostViewed',
    'reports' => 'merchant/merchantDetails/Reports',
    'request-pay' => 'merchant/merchantDetails/paymentRequest',
    'add-product' => 'merchant/products/addProduct',
    'edit-product' => 'merchant/products/Edit',
    'delete-product' => 'merchant/products/deleteproduct',
    'view-product' => 'merchant/products/View',
    'my-products' => 'merchant/products/myProducts',
    'banking_accounts' => 'merchant/bankingDetails/details',
    'add-account' => 'merchant/bankingDetails/create',
    'products' => 'product/products',
    'my-account' => 'buyerDetails/MyAccount',
    'address-book' => 'buyerDetails/AddressBook',
    'change-password' => 'buyerDetails/ChangePassword',
    'messages' => 'merchant/merchantDetails/Messages',
    'edit-profile' => 'buyerDetails/EditProfile',
    'my-orders' => 'buyerDetails/MyOrders',
    'my-wishlist' => 'buyerDetails/Wishlist',
    'my-cart' => 'cart/Mycart',
    '<controller:\w+>/<id:\d+>' => '<controller>/view',
    '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
);

